Server:
  port:
    8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: rajesh
    password: rajesh@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

cache:
  cache-names: books
  caffeine:
    spec: maximumSize=500,expireAfterAccess=60s

